# Generated by Django 6.0 on 2025-12-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created']},
        ),
    ]
